"""Built-in themes for Clide."""

from clide.themes.builtin import (
    all_hallows_eve,
    christmas,
    dark_autumn,
    dracula,
    fall,
    gamma,
    gruvbox_dark,
    gruvbox_light,
    hacker_style,
    halloween,
    houston,
    monokai_winter,
    nord,
    one_dark,
    one_dark_pro,
    one_dark_teal,
    one_light,
    pro_hacker,
    santa_baby,
    summer_day,
    summer_night,
    winter_is_coming,
)

__all__ = [
    "summer_night",
    "summer_day",
    "one_dark",
    "one_dark_pro",
    "one_light",
    "dracula",
    "nord",
    "gruvbox_dark",
    "gruvbox_light",
    "one_dark_teal",
    "gamma",
    "winter_is_coming",
    "monokai_winter",
    "fall",
    "dark_autumn",
    "all_hallows_eve",
    "halloween",
    "christmas",
    "santa_baby",
    "pro_hacker",
    "hacker_style",
    "houston",
]
